### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by sanlangguo** [ice-lab/ice-scripts#91]
[HPM] Error occurred while trying to proxy request /d08f25d3db064a8b5efb.hot-update.json from 127.0.0.1:4444 to http://127.0.0.1:4444 (EADDRINUSE) (https://nodejs.org/api/errors.html#errors_common_system_er
rors)

**Comment by ClarkXia** [comment]
提供下具体的代理设置和问题复现步骤

**Comment by sanlangguo** [comment]
1.ice.config.js 配置详情如下

   const path = require('path');

    module.exports = {
     hash: true,
     entry: 'src/index.jsx',
     publicPath: './',
     outputDir: 'dist',
     plugins: [
     ['ice-plugin-fusion', {
      themePackage: '@icedesign/theme',
     }],
     ['ice-plugin-moment-locales', {
      locales: ['zh-cn'],
     }],
     ['ice-plugin-load-assets', {
     assets: {
     dev: ['https://unpkg.com/react@16.8.0/umd/react.development.js',           'https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js', 'https://unpkg.com/react-dom@16.8.0/umd/react-dom.development.js'],
        build: ['https://unpkg.com/react@16.8.0/umd/react.production.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js', 'https://unpkg.com/react-dom@16.8.0/umd/react-dom.production.min.js'],
      },
    }],
     ],
     alias: {
      '@': path.resolve(__dirname, './src/'),
      },
     chainWebpack: (config) => {
     config.devServer.hot(true);
     },
     define: {
      ENV: JSON.stringify(process.env.ENV),
     },
     proxy: {
      "/**": {
       "enable": true,
        "target": "http://127.0.0.1:4444" 或者 http://192.168.3.17:4444
	}
      }
     };

2.  axios 配置如下

     const service = axios.create({
       baseURL:  ‘https://exam.com’,
       headers: {
        'content-type': 'application/json;charset=UTF-8;',
      },
     });

3.然后访问 http://192.168.3.17:4444或者  http://127.0.0.1:4444，均出现  

 Error occurred while trying to proxy request /d08f25d3db064a8b5efb.hot-update.json from 127.0.0.1
:4444 to http://127.0.0.1:4444 (EADDRINUSE) (https://nodejs.org/api/errors.html#errors_common_system_er
rors)

Error occurred while trying to proxy request /api/mobile/management/login from 192.168.3.17:4444
to http://192.168.3.17:4444/ (ENOBUFS) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by ClarkXia** [comment]
默认 devserver 访问就是 `http://127.0.0.1:4444` ，不需要再代理了， 可以尝试下代理到其他地址是否正常
